# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
if {$argv == "synth_design"} {
  set retval [open_checkpoint RAM32.dcp]
  if { $retval == "checkpoint_RAM32" } {
  create_report "RAM32_synth_1_synth_report_utilization_0" "report_utilization -file RAM32_utilization_synth.rpt -pb RAM32_utilization_synth.pb"
  
  close_design
  }
}
