create_clock -period 400.000 -name sys_clk [get_ports sys_clk]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
#create_clock -period 400.000 -name clk [get_ports clk]
set_property PACKAGE_PIN M13 [get_ports clk]
#set_property PACKAGE_PIN Y18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets dclk]







#set_property IOSTANDARD LVCMOS33 [get_ports {din[31]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[30]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[29]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[28]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[27]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[26]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[25]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[24]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[23]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[22]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[21]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[20]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[16]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports dclk]
set_property IOSTANDARD LVCMOS33 [get_ports in_arr]
set_property PACKAGE_PIN A15 [get_ports reset]
#set_property PACKAGE_PIN Y21 [get_ports {din[31]}]
#set_property PACKAGE_PIN Y22 [get_ports {din[30]}]
#set_property PACKAGE_PIN AB21 [get_ports {din[29]}]
#set_property PACKAGE_PIN AB22 [get_ports {din[28]}]
#set_property PACKAGE_PIN U20 [get_ports {din[27]}]
#set_property PACKAGE_PIN V20 [get_ports {din[26]}]
#set_property PACKAGE_PIN W19 [get_ports {din[25]}]
#set_property PACKAGE_PIN W20 [get_ports {din[24]}]
#set_property PACKAGE_PIN Y19 [get_ports {din[23]}]
#set_property PACKAGE_PIN V18 [get_ports {din[22]}]
#set_property PACKAGE_PIN V19 [get_ports {din[21]}]
#set_property PACKAGE_PIN AA19 [get_ports {din[20]}]
#set_property PACKAGE_PIN AB20 [get_ports {din[19]}]
#set_property PACKAGE_PIN V17 [get_ports {din[18]}]
#set_property PACKAGE_PIN W17 [get_ports {din[17]}]
#set_property PACKAGE_PIN AA18 [get_ports {din[16]}]
#set_property PACKAGE_PIN AB18 [get_ports {din[15]}]
#set_property PACKAGE_PIN U17 [get_ports {din[14]}]
#set_property PACKAGE_PIN U18 [get_ports {din[13]}]
#set_property PACKAGE_PIN P14 [get_ports {din[12]}]
#set_property PACKAGE_PIN R14 [get_ports {din[11]}]
#set_property PACKAGE_PIN R18 [get_ports {din[10]}]
#set_property PACKAGE_PIN T18 [get_ports {din[9]}]
#set_property PACKAGE_PIN N17 [get_ports {din[8]}]
#set_property PACKAGE_PIN P17 [get_ports {din[7]}]
#set_property PACKAGE_PIN P15 [get_ports {din[6]}]
#set_property PACKAGE_PIN R16 [get_ports {din[5]}]
#set_property PACKAGE_PIN N13 [get_ports {din[4]}]
set_property PACKAGE_PIN D19 [get_ports {din[3]}]
set_property PACKAGE_PIN D17 [get_ports {din[2]}]
set_property PACKAGE_PIN C17 [get_ports {din[1]}]
set_property PACKAGE_PIN B20 [get_ports {din[0]}]
set_property PACKAGE_PIN A16 [get_ports {dout[31]}]
set_property PACKAGE_PIN A13 [get_ports {dout[30]}]
set_property PACKAGE_PIN A14 [get_ports {dout[29]}]
set_property PACKAGE_PIN B17 [get_ports {dout[28]}]
set_property PACKAGE_PIN B18 [get_ports {dout[27]}]
set_property PACKAGE_PIN C18 [get_ports {dout[24]}]
set_property PACKAGE_PIN C19 [get_ports {dout[23]}]
set_property PACKAGE_PIN F18 [get_ports {dout[20]}]
set_property PACKAGE_PIN A20 [get_ports {dout[17]}]
set_property PACKAGE_PIN A18 [get_ports {dout[16]}]
set_property PACKAGE_PIN A19 [get_ports {dout[15]}]
set_property PACKAGE_PIN F19 [get_ports {dout[14]}]
set_property PACKAGE_PIN F20 [get_ports {dout[13]}]
set_property PACKAGE_PIN D20 [get_ports {dout[12]}]
set_property PACKAGE_PIN C20 [get_ports {dout[11]}]
set_property PACKAGE_PIN C22 [get_ports {dout[10]}]
set_property PACKAGE_PIN B22 [get_ports {dout[9]}]
set_property PACKAGE_PIN B21 [get_ports {dout[8]}]
set_property PACKAGE_PIN A21 [get_ports {dout[7]}]
set_property PACKAGE_PIN E22 [get_ports {dout[6]}]
set_property PACKAGE_PIN D22 [get_ports {dout[5]}]
set_property PACKAGE_PIN E14 [get_ports {dout[4]}]
set_property PACKAGE_PIN F13 [get_ports {dout[3]}]
set_property PACKAGE_PIN F14 [get_ports {dout[2]}]
set_property PACKAGE_PIN E16 [get_ports {dout[1]}]
set_property PACKAGE_PIN D16 [get_ports {dout[0]}]
set_property PACKAGE_PIN E19 [get_ports dclk]
set_property PACKAGE_PIN E18 [get_ports in_arr]



set_property PACKAGE_PIN E13 [get_ports o_raddr_valid]
set_property PACKAGE_PIN D15 [get_ports o_rdata_finish]
set_property IOSTANDARD LVCMOS33 [get_ports o_raddr_valid]
set_property IOSTANDARD LVCMOS33 [get_ports o_rdata_finish]
set_property PACKAGE_PIN B13 [get_ports {dout[26]}]
set_property PACKAGE_PIN E21 [get_ports {dout[25]}]
set_property PACKAGE_PIN D21 [get_ports {dout[22]}]
set_property PACKAGE_PIN G21 [get_ports {dout[21]}]
set_property PACKAGE_PIN G22 [get_ports {dout[19]}]
set_property PACKAGE_PIN F21 [get_ports {dout[18]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF]
